### ISSUE TITLE
Variable autocomplete not showing up

### ISSUE THREAD

**Issue by ghost** [Sarrus1/sourcepawn-vscode#223] opened 2022-05-03 06:56 UTC
## Basic info

- **OS:** [Windows]
- **VSCode version:** Latest
- **Extension version:** Latest

## Further Information

This does not work.
![image](https://user-images.githubusercontent.com/104819853/166413965-3d46f3ee-09d9-49f7-a23b-83e7b1ad0eb0.png)

But this does.
![image](https://user-images.githubusercontent.com/104819853/166414055-1e728e8f-5d0d-4f69-837a-4a8e2ea5dcdd.png)

Both methods will not be able to do this when hovering on `target_count`.
![image](https://user-images.githubusercontent.com/104819853/166414256-6609fe5b-82f0-4b07-b3ce-7e5663c86cc3.png)

It is not caused by how I formatted my `ProcessTargetString` method.
It also happens with other types like
```
float pos[3], ang[3];
char a[2], b[2];
```
etc. Thank you for your hard work!

**Comment by Sarrus1** [comment] 2022-05-03 08:07
Hi,

Can you please try with the pre-release version v3.3.2? The extension is under full rework, so this bug might already be fixed.

Please let me know if this fixes the issue.

![prerelease](https://user-images.githubusercontent.com/63302440/166421809-a7d94354-c607-49a3-8bb3-638bb7e17fd1.PNG)

**Comment by Manhole5892** [comment] 2022-05-03 22:45
Nevermind, it is caused by how I formatted my `ProcessTargetString`.

![image](https://user-images.githubusercontent.com/104819853/166584427-cd2bc271-df5a-4c31-97fb-2e6a2c371c65.png)
![image](https://user-images.githubusercontent.com/104819853/166584273-bf7484a6-0176-4e18-b051-83c8fe683af7.png)
![image](https://user-images.githubusercontent.com/104819853/166584358-2fe36580-0f7b-4506-bcba-bdc39381249e.png)

However it does not happen with global variables.
![image](https://user-images.githubusercontent.com/104819853/166584864-f9ba01d5-e477-4844-860d-fd133a031a34.png)

So it only happens with local variables. It is the same on the pre-release. Thank you for your help.

**Comment by Sarrus1** [comment] 2022-05-11 14:47
Fixed in #221

**Closed** 2022-06-21 21:28 UTC
Labels: bug
