### ISSUE TITLE
code coloring issues

### ISSUE THREAD

**Issue by ProjectSky** [Sarrus1/sourcepawn-vscode#341] opened 2023-09-29 12:23 UTC
# Basic informations

- **OS:** [Windows]
- **VSCode version:** Latest
- **Extension version:** Latest

# Further Information

![image](https://github.com/Sarrus1/sourcepawn-vscode/assets/16351827/0263c7a1-1da6-4343-9394-a70ed92b8df8)

# To Reproduce
idk how it happened, I just opened working directory and edited some script files

# Code to reproduce the behaviour

# Expected behaviour

# Error messages

**Comment by Sarrus1** [comment] 2023-10-02 13:34
Thank you for reporting.

Does this eventually go away?
What happens if you restart the server?

**Comment by ProjectSky** [comment] 2023-10-02 13:51
> Thank you for reporting.
> 
> Does this eventually go away? What happens if you restart the server?

* If I disable server, code coloring works again. restart server will not change anything

* some log
```
[Error - 21:48:10] Request textDocument/documentSymbol failed.
Error: name must not be falsy
	at s.validate (c:\Users\skyor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:103:16960)
	at new s (c:\Users\skyor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:103:17255)
	at ye (c:\Users\skyor\.vscode\extensions\sarrus.sourcepawn-vscode-6.0.2-win32-x64\dist\spIndex.js:34:73456)
	at ye (c:\Users\skyor\.vscode\extensions\sarrus.sourcepawn-vscode-6.0.2-win32-x64\dist\spIndex.js:34:73637)
	at o (c:\Users\skyor\.vscode\extensions\sarrus.sourcepawn-vscode-6.0.2-win32-x64\dist\spIndex.js:34:48563)
	at Object.tj [as map] (c:\Users\skyor\.vscode\extensions\sarrus.sourcepawn-vscode-6.0.2-win32-x64\dist\spIndex.js:34:48649)
	at Object.wr [as asDocumentSymbols] (c:\Users\skyor\.vscode\extensions\sarrus.sourcepawn-vscode-6.0.2-win32-x64\dist\spIndex.js:34:73423)
	at c (c:\Users\skyor\.vscode\extensions\sarrus.sourcepawn-vscode-6.0.2-win32-x64\dist\spIndex.js:38:56041)
	at async s.provideDocumentSymbols (c:\Users\skyor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:109:38034)
```

![202310022144](https://github.com/Sarrus1/sourcepawn-vscode/assets/16351827/b7bdb0b9-a79b-4242-a7ad-3199d591d636)

**Comment by Sarrus1** [comment] 2023-10-02 14:04
Thanks, can you send me the project you are working on so that I can reproduce please?

**Comment by ProjectSky** [comment] 2023-10-05 10:59
> Thanks, can you send me the project you are working on so that I can reproduce please?

here is the working directory/code to reproduce this issue
[sp.zip](https://github.com/Sarrus1/sourcepawn-vscode/files/12817559/sp.zip)

**Comment by Sarrus1** [comment] 2023-10-05 17:09
Weird it does not happen for me... Can you try on v6.1.0? I fixed a lot of preprocessor stuff.

<img width="1107" alt="ex" src="https://github.com/Sarrus1/sourcepawn-vscode/assets/63302440/16d9d159-263e-4320-8837-bd0d0d733b27">

**Comment by Sarrus1** [comment] 2023-10-05 17:11
Moving the `symbolRequest` bug to #345.

**Comment by ProjectSky** [comment] 2023-10-06 09:00
> Weird it does not happen for me... Can you try on v6.1.0? I fixed a lot of preprocessor stuff.

Strange, I'm using v6.1.0, I'll switch to a clean environment and retest it.

**Comment by Sarrus1** [comment] 2023-10-06 09:03
Can you try setting the logs to DEBUG as well?

**Comment by ProjectSky** [comment] 2023-10-06 10:08
> Can you try setting the logs to DEBUG as well?

[debug.txt](https://github.com/Sarrus1/sourcepawn-vscode/files/12829685/debug.txt)

**Comment by Sarrus1** [comment] 2023-10-06 10:31
Ok two more things:

- Your includesDirectories setting is empty, is it intentional?
- Do "ctrl + shift + p" and type "debug pre sourcepawn". And send me the output please.

**Comment by ProjectSky** [comment] 2023-10-06 10:43
> Ok two more things:
> 
> * Your includesDirectories setting is empty, is it intentional?
> * Do "ctrl + shift + p" and type "debug pre sourcepawn". And send me the output please.

1: yes (nothing will change even if I set it)
2: unknown command debug pre sourcepawn

![image](https://github.com/Sarrus1/sourcepawn-vscode/assets/16351827/fc74114f-b447-45dc-bed7-75c66ea69f06)

[trace.txt](https://github.com/Sarrus1/sourcepawn-vscode/files/12830097/trace.txt)

**Comment by Sarrus1** [comment] 2023-10-06 10:45
Sorry I mixed up the name:

https://github.com/Sarrus1/sourcepawn-vscode/blob/main/editors/code/package.json#L136

Should be "reveal preprocessed document"

**Comment by ProjectSky** [comment] 2023-10-06 10:47
> Sorry I mixed up the name:
> 
> https://github.com/Sarrus1/sourcepawn-vscode/blob/main/editors/code/package.json#L136
> 
> Should be "reveal preprocessed document"

[trace.txt](https://github.com/Sarrus1/sourcepawn-vscode/files/12830141/trace.txt)

**Comment by Sarrus1** [comment] 2023-10-06 10:50
Thanks, can you also send a screenshot of your screen?
I think the command opens a panel on the right.
I need the two documents side by side please.

The output you sent me is encoded in utf-8 so the chinese characters are not properly rendered :/

**Comment by ProjectSky** [comment] 2023-10-06 10:52
> Thanks, can you also send a screenshot of your screen? I think the command opens a panel on the right. I need the two documents side by side please.
> 
> The output you sent me is encoded in utf-8 so the chinese characters are not properly rendered :/

![image](https://github.com/Sarrus1/sourcepawn-vscode/assets/16351827/0883441b-813f-4f14-a526-6f26a16b787a)

**Comment by Sarrus1** [comment] 2023-10-06 10:58
Ok so on the screenshot the coloring errors are because the macros are expanded and the servers "sees" the tokens that were expanded.
This I can fix.

But on the very first screenshot you sent, the highlighting errors are not on the same line as the macros, can you send a screenshot where there is a highlighting error on a line that does not have a macro please?

**Comment by ProjectSky** [comment] 2023-10-06 11:03
It seems that code highlight issues only occur after macros

**Comment by Sarrus1** [comment] 2023-10-06 11:11
Ok this was probably fixed in 0.12.0 of the LSP, with either the deadlock fix or the preprocessor fix.
I am closing this issue, but if the bug reappears **on a line that does not have a macro**, please feel free to reopen this issue.

I am tracking the macro line highlight issue in #333.

**Closed by Sarrus1** 2023-10-06 11:11 UTC
Labels: bug, question, sourcepawn-lsp

**Comment by ProjectSky** [comment] 2023-10-06 11:18
Thank you for your hard work. By the way, I'd like to offer some support, but buymeacoffee cannot be used in China (:

**Comment by Sarrus1** [comment] 2023-10-06 18:04
Thanks! I have a paypal as well: omegasix0611@gmail.com

Glad you like the extension!

**Comment by ProjectSky** [comment] 2023-10-06 18:52
> Thanks! I have a paypal as well: [omegasix0611@gmail.com](mailto:omegasix0611@gmail.com)
> 
> Glad you like the extension!

paypal: Sorry, this recipient can’t accept payments right now :(

**Comment by Sarrus1** [comment] 2023-10-06 19:24
Oh crap right, try: `charleszablit@gmail.com`

**Comment by ProjectSky** [comment] 2023-10-07 01:29
> Oh crap right, try: `charleszablit@gmail.com`

Done

**Comment by Sarrus1** [comment] 2023-10-07 12:26
Thank you!
